{% set name = "genesis2" %}
{% set version = "2.6" %}

{% set build = 1 %}
# ensure mpi is defined (needed for conda-smithy recipe-lint)
{% set mpi = mpi or 'nompi' %}

{% if mpi == 'nompi' %}
# prioritize nompi variant via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/Genesis-1.3-Version2/archive/v{{ version }}.tar.gz
  sha256: 68703ca29f1fe220b96ddf61a9fe664fef1c200745813ff891ed1557e62761a1

build:
  number: {{ build }}

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `pkg * mpi_mpich_*` for mpich
  # `pkg * mpi_*` for any mpi
  # `pkg * nompi_*` for no mpi

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

  {% if mpi != 'nompi' %}

  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*
  {% endif %}


requirements:
  build:
    - make
    - {{ compiler('c') }}                    # [not win]
    - {{ compiler('m2w64_c') }}              # [win]
    - {{ compiler('fortran') }}              # [not win]
    - {{ compiler('m2w64_fortran') }}        # [win]
    - cmake
    - openmpi                                # [build_platform != target_platform]
  host:
    - {{ mpi }}   # [mpi != 'nompi']
  run:
    - {{ mpi }}   # [mpi != 'nompi']


test:
  commands:
    - which genesis2  # [unix]
    - which genesis2-mpi  # [unix and mpi != 'nompi']
    - genesis2   # [win]

about:
  home: hhttps://github.com/slaclab/Genesis-1.3-Version
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: GENESIS 1.3 is a time-dependent three-dimensional FEL code.

  description: |
    GENESIS 1.3 is a time-dependent three-dimensional FEL code.
    It is focused to simulate single-pass free-electron lasers, 
    both FEL amplifier and SASE FEL, although the flexible input
    can be used to easily extend the capacity of GENESIS 1.3 to
    cover FEL oscillators or multistage set-ups.
  doc_url: http://genesis.web.psi.ch/
  dev_url: https://github.com/slaclab/Genesis-1.3-Version2

extra:
  recipe-maintainers:
    - hhslepicka
    - ChristopherMayes
