{% set name = "genesis2" %}
{% set version = "2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/Genesis-1.3-Version2/archive/v{{ version }}.tar.gz
  sha256: e807933ef5c3fa31a4f92158277c8973b1e9ea44e4275f269134dd353784abe3
  patches:
    - 0000-mem_size_windows.patch  # [win]

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}                    # [not win]
    - {{ compiler('m2w64_c') }}              # [win]
    - {{ compiler('fortran') }}              # [not win]
    - {{ compiler('m2w64_fortran') }}        # [win]
  host:
  run:

test:
  commands:
    - genesis2

about:
  home: hhttps://github.com/slaclab/Genesis-1.3-Version
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: GENESIS 1.3 is a time-dependent three-dimensional FEL code.

  description: |
    GENESIS 1.3 is a time-dependent three-dimensional FEL code.
    It is focused to simulate single-pass free-electron lasers, 
    both FEL amplifier and SASE FEL, although the flexible input
    can be used to easily extend the capacity of GENESIS 1.3 to
    cover FEL oscillators or multistage set-ups.
  doc_url: http://genesis.web.psi.ch/
  dev_url: https://github.com/slaclab/Genesis-1.3-Version2

extra:
  recipe-maintainers:
    - hhslepicka
    - ChristopherMayes
